sudo: false
dist: trusty
language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gdb
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gdb
      env: COMPILER=g++-5


before_install:

  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - BOOST_VERSION=1.60.0

  - if [[ ! -x ${DEPS_DIR}/b2/bin/b2 ]]; then
      mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR};
      if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.61.0; fi;

      if [[ "${BOOST_VERSION}" == "1.60.0" ]]; then BOOST_URL="https://github.com/boostorg/boost/archive/boost-1.60.0.tar.gz"; fi;
      if [[ "${BOOST_VERSION}" == "1.61.0" ]]; then BOOST_URL="https://github.com/boostorg/boost/archive/boost-1.61.0.tar.gz"; fi;
      if [[ "${BOOST_URL}" != "" ]]; then mkdir -p boost && travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost; fi;

      ls -a;

      cd boost/tools/build && ls -a && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2;
      cd ${TRAVIS_BUILD_DIR};
    fi

  -  export PATH=${DEPS_DIR}/b2/bin:${PATH}
  -  export BOOST_ROOT=${DEPS_DIR}/boost


script:
  - $CC --version
  - $CXX --version
  - |-
    JAM="using clang : : ${CXX} ;"

  - cd test
  - touch project-config.jam
  - echo "${JAM}" > project-config.jam
  - ./test.sh --toolset=clang
